* notes
Max & Sam idea from Hertz retreat: don't put different indices of refraction in silicon, just in insulator layers... can be a large difference since a small proportion of the signal is up in there

Rui, materials. Hafnium based materials... high-K. ALD film thickness control... K ~ 11-14, can go up to 20... 1 cycle gives you a sub-angstrom thickness... 0.28 angstroms per cycle... ALD at Harvard CNS has about 0.9 angstrom per cycle... 

	Question: can such a thin layer impact the index of refraction -- BUT key point... free carrier effect charge layer is the relevant layer...
	
	What we do need to worry about: dielectric breakdown or tunneling, film quality... 
	What we don't need to worry about: insulator itself being too thin to contain much of the wave
	
	dielectric breakdown is 2.5 megavolt per centimeter = 25 mV per angstrom
	
	--> 4 nm survives 1V
	
	... hmm, 20 * permittivity of free space / (4 nm) = 4 uF / cm^2 which is not quite enough...? 
		whereas if we could get 1 angstrom thickness without the dielectric breakdown that would suffice: 20 * permittivity of free space / (0.1 nm) in uF per square centimeter = 177
	
What about barium titanate with MBE?

	layer by layer titanates
	
	these have about an order of magnitude higher dielectric constant than the hafnium... perhaps a 1 nm layer...
	
	they don't know if this is possible to have in 1 nm thickness...
	
	or just strontium titanate
	
	sounding like 30 mW, epsilon / d = 10^11 corresponds to 1 nm thin layer with epsilon = 100 ... IF we can get the dielectric constant to be that high, that thin
	
	to do: look up ALD of barium titanate and strontium titanate
	
	to do: talk to Roy Gordon @ Harvard who is expert on ALD
	
	paper found by Max -- dielectric permittivity of 16 and 50 (after annealing)... strontium *tantalate*... 
	
	1-2 nm layers of the titanate?
	
	for strontium titanate thin films grown by ALD, permittivity is 180... thickness = 
	http://www.researchgate.net/publication/230540345_Atomic_Layer_Deposition_of_SrTiO3_Thin_Films_from_a_Novel_Strontium_PrecursorStrontiumbis%28triisopropyl_cyclopentadienyl%29
	"A major concern with the high permittivity oxides is the decrease of permittivity with decreasing film thickness, and this behavior was also observed here. Nevertheless, a per-mittivity of 100 was obtained with an annealed 50 nm film."
	
What about super-capacitors?
	
	These need electrical double layer liquid electrolyte to function.
	
	But, there are also solid state super-capacitors. 
	
	Lithium Floride (probably very toxic... used for infrared transparent windows)... thermal evaporation... very easy... go down to 50 nm
	
	10's of uF per centimeter squared... Sam: for us the sweet spot is 100 uF per square centimeter, because then it becomes comparable to the brain interface capacitance
	
Max idea: 

	liquid core waveguide... well accepted and very common in telecom
	tube of liquid inside dielectric shell
	
	thin geometry, but might be possible... could trade off space for materials properties and get a very high figure of merit
	
Ed: 

	increase the surface area... talk to Jorg... stacked capacitors with vias
	
Max: play trick and change wavelength? use something that is not silicon but still has free carrier dispersion...
	silicon carbide?
	zinc oxide?
	
Joel: what about the index of refraction of these materials... do we need to worry about mu in addition to epsilon...
	lets look up kramers kronig

Joel simulates alternating materials... n ~ 1 - 3, tune parameters
size of the free carrier layer ~ ?
read solar cell literature... max send PDF, basic solid state physics... linear shape? exponential?



solid state LiF super capacitors??  best ~10 uF

liquid core waveguides? with CSF?!

~10 stacked capacitors w/ vias instead of 1 single 



alt wg materials:
Silicon carbide (SiC)
Zinc oxide

* directives
- modify structure to have alternating gradient of refractive index 

                      nano sheet capacitor
 _______________________________________________________________
|  n1  |  n2  |  n1  |  n2  |  n1  |  n2  |  n1  |  n2  |  n1   |  where n1 ~1 and n2 ~3, with a gradient of refractive index in y direction
|_______________________________________________________________|
|                                                               |
|                                                               |
|                   Silicon waveguide                           |
|                                                               |
|                                                               |
|_______________________________________________________________|


- parameterize:
  - sx, sy      ; size x and y
  - n1, n2      ; refractive indices n1 and n2
  - gy, f       ; length of gradient in y direction, fn of the gradient (distribution of free charge carriers, converted to refractive index)




* scratch
ϵ = ϵ0 − (ω2p) / (ω2−γ2)

ω2p = Nq2 / ϵ0m∗

n = (ϵμ)^(.5)




n = ((ϵ0 − (Nq2 / ϵ0 m∗) / (ω2 − γ2)) μ )^(.5)
